name: Push Canary Release
on:
  push:
    branches: [main]
jobs:
  canary-release-to-npm:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Configure Git User
        run: |
          git config --global user.email "ci@innatical.com"
          git config --global user.name "ci@$GITHUB_ACTOR"

      - name: Verify NPM permissions
        run: npm whoami
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Publish to NPM
        run: |
          lerna publish --canary --no-verify-access --yes
