name: Push Canary Release
on:
  push:
    branches: [main]
jobs:
  canary-release-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Configure Git User
        run: |
          git config --global user.email "ci@innatical.com"
          git config --global user.name "ci@$GITHUB_ACTOR"
      - name: Install dependencies
        run: yarn install
      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to NPM
        run: |
          lerna publish --canary --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
