name: Push Release
on:
  release:
    types: [created]
jobs:
  release-to-npm:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Configure Git User
        run: |
          git config --global user.email "ci@innatical.com"
          git config --global user.name "ci@$GITHUB_ACTOR"
      - name: Install dependencies
        run: yarn install
      - name: Publish to NPM
        run: |
          lerna publish --yes
